# GMAIL ACCOUNT CREDENTIAL USED FOR SENDING EMAILS
MY_ADDRESS = "testingforstars@gmail.com"
PASSWORD = "satkohli"

# CREDENTIALS FOR OAUTH
APP_SECRET_KEY = "123ABC"
GOOGLE_CLIENT_ID = (
    "530865719446-p1dhlt0f0deg9pti3ms1a3jcs44cdjfb.apps.googleusercontent.com"
)
GOOGLE_CLIENT_SECRET = "M35Z3XBhGqfjou0HaSQ0-k1n"